# Generated by Django 3.2.7 on 2021-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=20)),
                ('membership_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('number_of_community_health_workers', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
