# Generated by Django 3.2.7 on 2021-11-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_first_name', models.CharField(max_length=15)),
                ('contact_persons_last_name', models.CharField(max_length=20)),
                ('ID_number', models.CharField(max_length=8)),
                ('household_area', models.CharField(max_length=30)),
                ('number_of_household_members', models.IntegerField()),
                ('contact_persons_income', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients_first_name', models.CharField(max_length=15)),
                ('patients_last_name', models.CharField(max_length=20)),
                ('home_area', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('Cough', 'Cough'), ('Diarrhoea', 'Diarrhoea'), ('Epilepsy', 'Epilepsy'), ('Pregnancy', 'Pregnancy'), ('Nutrition', 'Nutrition'), ('Family planning', 'Family planning'), ('Other', 'Other')], max_length=30)),
                ('have_you_visited_any_hospital_before', models.BooleanField()),
                ('which_one', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('brief_description_of_the_condition', models.TextField()),
                ('referree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
        migrations.CreateModel(
            name='MotherAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('have_you_lost_an_infant_before', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('how_many', models.PositiveSmallIntegerField()),
                ('how_far_long_is_your_pregnancy', models.PositiveSmallIntegerField()),
                ('what_is_your_expected_day_of_delivery', models.DateField()),
                ('do_you_have_any_complications', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('describe_the_complication', models.CharField(max_length=50)),
                ('do_you_go_to_clinic', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('which_clinic', models.CharField(max_length=20)),
                ('when_was_the_last_time_you_visited_a_clinic', models.DateField()),
                ('do_take_any_supplements', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('if_yes_which_one', models.PositiveSmallIntegerField()),
                ('do_you_have_Linda_Mama', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('remarks', models.TextField()),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
        migrations.CreateModel(
            name='Mother_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothers_first_name', models.CharField(max_length=15)),
                ('mothers_last_name', models.CharField(max_length=20)),
                ('home_area', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('Cough', 'Cough'), ('Diarrhoea', 'Diarrhoea'), ('Epilepsy', 'Epilepsy'), ('Pregnancy', 'Pregnancy'), ('Nutrition', 'Nutrition'), ('Family planning', 'Family planning'), ('Other', 'Other')], max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('referree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=12)),
                ('number_of_pregnant_women', models.PositiveSmallIntegerField()),
                ('number_of_newborns', models.PositiveSmallIntegerField()),
                ('number_of_children_under_5_years_of_age', models.PositiveSmallIntegerField()),
                ('number_of_vaccinated_children', models.PositiveSmallIntegerField()),
                ('number_of_people_living_with_diabilities', models.PositiveSmallIntegerField()),
                ('number_of_elderly', models.PositiveSmallIntegerField()),
                ('number_of_orphans', models.PositiveSmallIntegerField()),
                ('number_of_persons_living_with_chronic_diseases', models.PositiveSmallIntegerField()),
                ('do_you_have_any_sick_person_in_this_household', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('do_you_have_health_insurance', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('remarks', models.TextField()),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childs_first_name', models.CharField(max_length=15)),
                ('childs_last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('has_she_or_she_been_vaccinated', models.BooleanField(null=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
    ]
