# Generated by Django 3.2.7 on 2021-11-03 05:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ID_number', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(default='janedoe@gmail.com', max_length=254)),
                ('region_or_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_first_name', models.CharField(max_length=15)),
                ('contact_persons_last_name', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ID_number', models.CharField(max_length=8)),
                ('household_area', models.CharField(max_length=30)),
                ('number_of_household_members', models.IntegerField()),
                ('contact_persons_income', models.PositiveBigIntegerField()),
                ('number_of_pregnant_women', models.PositiveSmallIntegerField()),
                ('number_of_newborns', models.PositiveSmallIntegerField()),
                ('number_of_children_under_5_years_of_age', models.PositiveSmallIntegerField()),
                ('number_of_people_living_with_diabilities', models.PositiveSmallIntegerField()),
                ('number_of_elderly', models.PositiveSmallIntegerField()),
                ('number_of_orphans', models.PositiveSmallIntegerField()),
                ('number_of_persons_living_with_chronic_diseases', models.PositiveSmallIntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
