# Generated by Django 3.2.4 on 2021-11-16 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='contact_persons_income',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients_first_name', models.CharField(max_length=15)),
                ('patients_last_name', models.CharField(max_length=20)),
                ('home_area', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=20)),
                ('condition', models.CharField(choices=[('Cough', 'Cough'), ('Diarrhoea', 'Diarrhoea'), ('Epilepsy', 'Epilepsy'), ('Pregnancy', 'Pregnancy'), ('Nutrition', 'Nutrition'), ('Family planning', 'Family planning')], max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('brief_description_of_the_condition', models.TextField()),
                ('referree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chw.households')),
            ],
        ),
    ]
